### PR TITLE
Add guard clause to stub.py

### PR DESCRIPTION
**Pull request by KentBeck**
#tidying

### CODE REVIEW

**Comment by Bogdanp** [comment]
Thanks!

**Comment by KentBeck** [comment]
You're welcome. I was pointed at your project by Keith Adams & I really like the code & concept. I'm writing a book on software design (tidyfirst.substack.com) & I want to use it for examples. This will involve a bunch of little PRs like this one. I hope you don't mind.

**Comment by KentBeck** [comment]
I have a couple of things I'd like to discuss if you have time.

**Comment by Bogdanp** [comment]
@KentBeck feel free to e-mail me. You can find my e-mail on my GH profile.

**Comment by danieltkach** [comment]
I started reading the book a moment ago, and writing about it in my company's internal social media, "Viva Engage" (former "Yammer").
@KentBeck I foresee it's going to make me grow as a developer in every sense.

**Comment by RajatChoudhary999** [comment]
Just Started reading the book "Tidy" Finished 5 chapters and I'm loving it, Short, Selective and Concise.

**Comment by xieyuheng** [comment]
I love you @KentBeck, you truly made me feel confident and safe when programming :)

**Pull request merged**
