### PR TITLE
Update rabbitmq.py

### PR DESCRIPTION
**Pull request by evstratbg**
support `dramatiq_dead_message_ttl` env variable to dynamically change it

### CODE REVIEW

**Comment by Bogdanp** [comment]
Thanks. It looks like there are linting errors here and I think the types don't line up. Doesn't the env var need to be converted to an integer?

**Comment by evstratbg** [comment]
> Thanks. It looks like there are linting errors here and I think the types don't line up. Doesn't the env var need to be converted to an integer?

Right. Should I add more complex checks or just add int()?

**Comment by Bogdanp** [comment]
Just int is fine, thanks!

**Comment by Bogdanp** [comment]
Thanks, this has been merged with rebase.

**Pull request closed without merging**
