### PR TITLE
Access broker in object attributes

### PR DESCRIPTION
**Pull request by bersace**
Hi @Bogdanp,

I expected that Dramatiq would be able to resolve deep attribute access like you can define in `pkg_resources` entry-point. This PR add this behaviour, based on pkg_resources implementation ( https://github.com/pypa/setuptools/blob/ad98fcb350fa3ce63389520a391e23274de11064/pkg_resources/__init__.py#L2426-L2434 ).

This ease integration with e.g. Flask by accepting `dramatiq some_module:app.broker` construction.

What do you think of this ?

### CODE REVIEW

**Comment by Bogdanp** [comment]
This is good, but it needs a test before I can merge it. Check out `test_cli.py`.

**Comment by bersace** [comment]
Hi @Bogdanp. Thanks for pointing at it. I choosed to update existing test to both check deep attribute accessing and instance check.

Appveyor doesn't have build logs for me. Do i need privileges or something else to have logs ?

**Comment by bersace** [comment]
@Bogdanp beware it's fixup. You either need to squash commits or let me rebase --autosquash before merging ! Thanks !

**Comment by Bogdanp** [comment]
Thanks. This has now been merged w/ rebase.

**Pull request closed without merging**
