### PR TITLE
Facilitate overwriting of Consumer class

### PR DESCRIPTION
**Pull request by AndreCimander**
This is just a very minor nitpick, feel free to close it, but it would be nice to change the class of the Consumer without the need to completly replicate and overwrite `.consume()` :)

### CODE REVIEW

**Comment by Bogdanp** [comment]
This seems OK to me, but how about making it a class property instead?

**Comment by AndreCimander** [comment]
I was thinking about adding it as a cls property, but the consumer classes are not yet defined.


We could go the `@property` route, though, this would also make it easier to add logic if one desires. How would you like it named? `consumer` / `consumer_class`? :)


```
    @property
    def consumer_class(self):
        return _RedisConsumer
```

**Comment by Bogdanp** [comment]
Ah, right, that makes sense. Yeah, `consumer_class` sounds good.

**Comment by Bogdanp** [comment]
Thanks! I have squashed and merged this.

**Pull request closed without merging**
