### PR TITLE
RabbitMQ priority

### PR DESCRIPTION
**Pull request by davidt99**
Add support to rabbitmq priority queue.
Examples and documentation are still missing, I'll add them after you'll approve it.
The idea is to send the message with options like this:
```python
some_actot.send_with_options(broker_priority=5)
```

### CODE REVIEW

**Comment by davidt99** [comment]
And fixed a bug while writing tests: The worker will start consuming even if it's stopped.

**Comment by davidt99** [comment]
I was trying to do it with a middleware but the declare queue callback doesn't get the actor option, as described in #91

**Comment by ryanhiebert** [comment]
> I was trying to do it with a middleware but the declare queue callback doesn't get the actor option, as described in #91

Interesting. My thinking is that since queues may be shared between actors, pulling the max_priority off the actor probably doesn't make sense. And even then, the queue need not be declared on the actor, so it's at best an unreliable way to set it. I think what you've written here makes the most sense.

**Comment by davidt99** [comment]
@Bogdanp I rebased and the tests are passing, can you take a look? There are more improvements that I want to make into dramatiq but this PR is on the shelf for almost a month...

**Comment by Bogdanp** [comment]
Thanks! I merged most of your changes with rebase.  I added explicit support for pausing consumers in tests as opposed to what you had w/ not starting them at all.

**Pull request closed without merging**
