### PR TITLE
Adds support for specifying log and PID files

### PR DESCRIPTION
**Pull request by najamansari**
PID files are essential for automated deployments. Similarly, storing logs in a file makes debugging easier (
and as a bonus, you can do log analytics through ELK!).

### CODE REVIEW

**Comment by Bogdanp** [comment]
Thanks for contributing this! Make sure you add yourself to the contributors list per [the contributing guide](https://dramatiq.io/contributing.html). I'll pick this up afterwards and make some minor tweaks as well as add some tests this weekend and then merge it.

**Comment by najamansari** [comment]
Done!

**Comment by Bogdanp** [comment]
Thanks! I merged your changes with rebase here: https://github.com/Bogdanp/dramatiq/compare/a329d8fd6b8ffc3c1a28b7b82a0443abc82888c5...HEAD

I made a few changes to harden the code as well as fix a couple bugs to do w/ logging (the way you had it set up here, logs weren't coalesced in a file so you could end up w/ partial logs).

**Comment by najamansari** [comment]
Awesome, I just realized I missed out a couple of important cases!

**Pull request closed without merging**
