### PR TITLE
Miscellaneous minor changes

### PR DESCRIPTION
**Pull request by dimrozakis**
Hi @Bogdanp 

This PR contains several small changes. Please check the commit log for details. The changes are unrelated but each one is very small and separated into its own commit with descriptive message. Please tell me what you think. If you'd like me to split it into multiple PRs, just say the word.

### CODE REVIEW

**Comment by Bogdanp** [comment]
Thanks! I think I'm only going to keep the `isatty` change. The change to store the exception type and message separately seems redundant with the `exn` field. I'd either want to keep it as-is or just update the `exn` field to make it a dictionary containing `type` and `message` fields.

**Comment by Bogdanp** [comment]
I've merged the isatty change with rebase. Thanks again!

**Comment by dimrozakis** [comment]
Hi @Bogdanp 

Thanks for merging the `isatty` change.

>The change to store the exception type and message separately seems redundant with the exn field. I'd either want to keep it as-is or just update the exn field to make it a dictionary containing type and message fields.

They are redundant. I want to be able to differentiate between different exceptions on the caller's side without having to parse a string to extract exception type name and message. Turning `exn` into a dictionary would be great, the only reason I implemented with additional fields was in order not to break compatibility.

The other changes (.gitignore & compose for tests) aided me in development and I thought of sharing them in case you wanted to include them, they're minor changes and don't really matter anyway.

**Comment by Bogdanp** [comment]
> They are redundant. I want to be able to differentiate between different exceptions on the caller's side without having to parse a string to extract exception type name and message. Turning exn into a dictionary would be great, the only reason I implemented with additional fields was in order not to break compatibility.

Yup. I figured. I don't think we have to worry about breaking compatibility since the change hasn't been officially released yet so we can definitely make the change now. Let me know if you want to do it yourself.

**Pull request closed without merging**
